plugins:
  - jekyll-relative-links
theme: slate
relative_links:
  enabled: true
  collections: true
  permalink: pretty
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md